export type Accent = "primary" | "secondary" | "blue" | "green" | "white";
export type ShapeVariant = "square" | "circle" | "triangle";

export type Project = {
  slug: string;
  title: string;
  subHeader: string;
  context: string;
  description: string;
  bodyText: string;
  url?: string;
  images: string[];
  tags: string[];
  category: string;
  summary: string;
  services: string[];
  year: string;
  challenge: string;
  process: string;
  outcome: string;
  accent: Accent;
  thumbnailShape: ShapeVariant;
  thumbnailHoverShape: ShapeVariant;
  heTitle?: string;
  heSubHeader?: string;
  heContext?: string;
  heDescription?: string;
  heTags?: string[];
  status?: string;
  heStatus?: string;
  discipline?: string;
  heDiscipline?: string;
  descriptor?: string;
  heDescriptor?: string;
  opener?: string;
  heOpener?: string;
  narrativeChallenge?: string;
  narrativeApproach?: string;
  narrativeDecision?: string;
  heNarrativeChallenge?: string;
  heNarrativeApproach?: string;
  heNarrativeDecision?: string;
  /** Optional subheaders for the three story slots. Empty string = no heading. */
  narrativeChallengeLabel?: string;
  narrativeApproachLabel?: string;
  narrativeDecisionLabel?: string;
  heNarrativeChallengeLabel?: string;
  heNarrativeApproachLabel?: string;
  heNarrativeDecisionLabel?: string;
};
